import type { RawAppealEntity } from './appeal.raw-entity';
import type { RawAttendanceRecordEntity } from './attendance-record.raw-entity';
import type { RawAttendanceSessionEntity } from './attendance-session.raw-entity';
import type { RawClassEntity } from './class.raw-entity';
import type { RawClassMemberEntity } from './class-member.raw-entity';
import type { RawDepartmentEntity } from './department.raw-entity';
import type { RawFaceEmbeddingEntity } from './face-embedding.raw-entity';
import type { RawFaceImageEntity } from './face-image.raw-entity';
import type { RawFaceRegistrationRequestEntity } from './face-registration-request.raw-entity';
import type { RawFileEntity } from './file.raw-entity';
import type { RawLeaveRequestEntity } from './leave-request.raw-entity';
import type { RawNotificationEntity } from './notification.raw-entity';
import type { RawRecognitionEventEntity } from './recognition-event.raw-entity';
import type { RawRefreshTokenEntity } from './refresh-token.raw-entity';
import type { RawRoleEntity } from './role.raw-entity';
import type { RawSpecializationEntity } from './specialization.raw-entity';

export interface RawUserEntity {
  id: number;
  fullName: string;
  email: string;
  passwordHash: string;
  roleId: number;
  avatarFileId: number | null;
  phone: string | null;
  departmentId: number | null;
  specializationId: number | null;
  createdAt: Date;
  updatedAt: Date;
  role: RawRoleEntity;
  avatarFile: RawFileEntity | null;
  department: RawDepartmentEntity | null;
  specialization: RawSpecializationEntity | null;
  refreshTokens: RawRefreshTokenEntity[];
  taughtClasses: RawClassEntity[];
  classMemberships: RawClassMemberEntity[];
  uploadedFiles: RawFileEntity[];
  faceRegistrationRequests: RawFaceRegistrationRequestEntity[];
  reviewedFaceRegistrationRequests: RawFaceRegistrationRequestEntity[];
  faceImages: RawFaceImageEntity[];
  reviewedFaceImages: RawFaceImageEntity[];
  faceEmbeddings: RawFaceEmbeddingEntity[];
  createdAttendanceSessions: RawAttendanceSessionEntity[];
  attendanceRecords: RawAttendanceRecordEntity[];
  recognitionEvents: RawRecognitionEventEntity[];
  leaveRequests: RawLeaveRequestEntity[];
  reviewedLeaveRequests: RawLeaveRequestEntity[];
  appeals: RawAppealEntity[];
  reviewedAppeals: RawAppealEntity[];
  notifications: RawNotificationEntity[];
}
