export const REPOSITORY_TOKENS = {
  AUTH: 'AUTH_REPOSITORY',
  USERS: 'USERS_REPOSITORY',
  CLASSES: 'CLASSES_REPOSITORY',
  FACES: 'FACES_REPOSITORY',
  ATTENDANCE: 'ATTENDANCE_REPOSITORY',
  REAL_TIME: 'REAL_TIME_REPOSITORY',
  RECORDS: 'RECORDS_REPOSITORY',
  EXCEPTIONS: 'EXCEPTIONS_REPOSITORY',
  REQUESTS: 'REQUESTS_REPOSITORY',
  NOTIFICATIONS: 'NOTIFICATIONS_REPOSITORY',
} as const;
